# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SAP
version:      0.01
version_from: SAP.pm
installdirs:  site
requires:
    Compress::Zlib:                1.14
    IO::Socket::Multicast:         0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
